env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - id: default
    skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - 'merge conflict'
      - 'Merge pull request'
      - 'Merge remote-tracking branch'
      - 'Merge branch'
  groups:
    - title: ':syringe: Dependency updates'
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 11000
    - title: ':fire: New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: ':bug: Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: ':book: Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 500
    - title: ':white_check_mark: Test'
      regexp: "^.*test[(\\w)]*:+.*$"
      order: 600
    - title: ':hammer: Other work'
      order: 900

milestones:
  - close: true

release:
  name_template: "v{{.Version}}"
  draft: false
  mode: append
  header: |
    ### Present this new release :sweat_drops:
    Please provide feedback in discussions and report bugs on the issue tracker. Thanks!
  footer: |
    **See all changes**: https://github.com/td-autoprofi/partner-go-services/compare/{{ .PreviousTag }}...{{ .Tag }}